import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/app/Header";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

async function fetchUser() {
    const res = await fetch('http://localhost:8999/api/v1/auth/check?flag=false',
        {
            method: 'GET',
            credentials: 'include',
        });
    const data = await res.json();
    return data;
}

export default async function RootLayout({children}: Readonly<{
    children: React.ReactNode
}>) {
    const result = await fetchUser();
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header data={result}/>
        {children}
        </body>
        </html>
    );
}
